/* ==========================================================================
   BGM MUSIC PATTERNS
   ========================================================================== */

import { NOTES } from './notes.js';

export type PatternArray = Array<number | null>;

// 192-step Retro Chiptune Adaptation: "In the Hall of the Mountain King" (Edvard Grieg)
export const BASS_PATTERN: PatternArray = [
    // --- Phase 1: Clear Staccato Motifs (Steps 0–63) ---
    // A minor
    NOTES.A2, null, NOTES.E3, null, NOTES.A2, null, NOTES.C3, null,
    NOTES.A2, null, NOTES.E3, null, NOTES.C3, null, NOTES.E3, null,

    // E major / dominant
    NOTES.E2, null, NOTES.B2, null, NOTES.E3, null, NOTES.Gs2, null,

    // C minor colour beneath G–Eb melody
    NOTES.C2, null, NOTES.G2, null, NOTES.C3, null, NOTES.G2, null,

    // A minor
    NOTES.A2, null, NOTES.E3, null, NOTES.A2, null, NOTES.C3, null,

    // Rising A-minor arpeggio
    NOTES.A2, null, NOTES.C3, null, NOTES.E3, null, NOTES.A3, null,

    // C major
    NOTES.C2, null, NOTES.G2, null, NOTES.C3, null, NOTES.E3, null,

    // E dominant turnaround
    NOTES.E2, null, NOTES.B2, null, NOTES.E3, null, NOTES.Gs2, null,


    // --- Phase 2: Driving Ostinato (Steps 64–127) ---
    // A minor
    NOTES.A2, NOTES.A2, NOTES.E3, NOTES.A2,
    NOTES.C3, NOTES.A2, NOTES.E3, NOTES.A2,

    NOTES.A2, NOTES.E3, NOTES.A3, NOTES.E3,
    NOTES.C3, NOTES.E3, NOTES.A2, NOTES.E3,

    // E major / dominant
    NOTES.E2, NOTES.E2, NOTES.B2, NOTES.E3,
    NOTES.Gs2, NOTES.B2, NOTES.E3, NOTES.B2,

    // C minor colour
    NOTES.C2, NOTES.C2, NOTES.G2, NOTES.C3,
    NOTES.G2, NOTES.C3, NOTES.G2, NOTES.C3,

    // A minor
    NOTES.A2, NOTES.A2, NOTES.E3, NOTES.A2,
    NOTES.C3, NOTES.A2, NOTES.E3, NOTES.A2,

    // Ascending A-minor variation
    NOTES.A2, NOTES.C3, NOTES.E3, NOTES.A3,
    NOTES.E3, NOTES.C3, NOTES.E3, NOTES.C3,

    // C major
    NOTES.C2, NOTES.C2, NOTES.G2, NOTES.C3,
    NOTES.E3, NOTES.C3, NOTES.G2, NOTES.C3,

    // E dominant turnaround
    NOTES.E2, NOTES.E2, NOTES.B2, NOTES.E3,
    NOTES.Gs2, NOTES.B2, NOTES.E3, NOTES.B2,


    // --- Phase 3: Structured Crescendo & Finale (Steps 128–191) ---
    // A minor pulse
    NOTES.A2, NOTES.A2, NOTES.E3, NOTES.A2,
    NOTES.A3, NOTES.A2, NOTES.E3, NOTES.A2,

    // C major pulse
    NOTES.C2, NOTES.C2, NOTES.G2, NOTES.C3,
    NOTES.E3, NOTES.C3, NOTES.G2, NOTES.C3,

    // E dominant pulse
    NOTES.E2, NOTES.E2, NOTES.B2, NOTES.E3,
    NOTES.Gs2, NOTES.B2, NOTES.E3, NOTES.B2,

    // A minor resolving toward E
    NOTES.A2, NOTES.A2, NOTES.E3, NOTES.A3,
    NOTES.C3, NOTES.A2, NOTES.E2, NOTES.E2,

    // Descending breakdown
    NOTES.E2, null, NOTES.B2, null,
    NOTES.E3, null, NOTES.B2, null,

    NOTES.D2, null, NOTES.A2, null,
    NOTES.C2, null, NOTES.B2, null,

    // Final A minor → E dominant exchange
    NOTES.A2, NOTES.A2, NOTES.E3, NOTES.A3,
    NOTES.E2, NOTES.B2, NOTES.E3, NOTES.B2,

    // Final tonic
    NOTES.A2, null, NOTES.E3, null,
    NOTES.A2, null, null, null
];

export const MELODY_PATTERN: PatternArray = [
    // --- Phase 1: Lower Octave Theme (Steps 0 - 63) ---
    NOTES.A4, null, NOTES.B4, null, NOTES.C5, null, NOTES.D5, null,
    NOTES.E5, null, NOTES.C5, null, NOTES.E5, null, null, null,
    NOTES.Gs4, null, NOTES.E5, null, NOTES.Gs4, null, null, null,
    NOTES.G4, null, NOTES.Eb5, null, NOTES.G4, null, null, null,
    NOTES.A4, null, NOTES.B4, null, NOTES.C5, null, NOTES.D5, null,
    NOTES.E5, null, NOTES.C5, null, NOTES.E5, null, NOTES.A5, null,
    NOTES.G5, null, NOTES.E5, null, NOTES.C5, null, NOTES.E5, null,
    NOTES.G5, null, null, null, NOTES.E5, null, null, null,

    // --- Phase 2: High Octave Intensity Rise (Steps 64 - 127) ---
    NOTES.A5, null, NOTES.B5, null, NOTES.C6, null, NOTES.D6, null,
    NOTES.E6, null, NOTES.C6, null, NOTES.E6, null, null, null,
    NOTES.Gs5, null, NOTES.E6, null, NOTES.Gs5, null, null, null,
    NOTES.G5, null, NOTES.Eb5, null, NOTES.G5, null, null, null,
    NOTES.A5, null, NOTES.B5, null, NOTES.C6, null, NOTES.D6, null,
    NOTES.E6, null, NOTES.C6, null, NOTES.E6, null, NOTES.A5, null,
    NOTES.G5, null, NOTES.E5, null, NOTES.C5, null, NOTES.E5, null,
    NOTES.G5, null, null, null, NOTES.E5, null, null, null,

    // --- Phase 3: Accelerating Crescendo & Climax (Steps 128 - 191) ---
    NOTES.A4, NOTES.B4, NOTES.C5, NOTES.D5, NOTES.E5, NOTES.F5, NOTES.E5, NOTES.D5,
    NOTES.C5, NOTES.B4, NOTES.A4, NOTES.Gs4, NOTES.A4, NOTES.B4, NOTES.C5, NOTES.D5,
    NOTES.E5, NOTES.F5, NOTES.Fs5, NOTES.Gs5, NOTES.A5, NOTES.B5, NOTES.C6, NOTES.D6,
    NOTES.E6, NOTES.D6, NOTES.C6, NOTES.B5, NOTES.A5, NOTES.Gs5, NOTES.F5, NOTES.E5,
    NOTES.E5, null, NOTES.E5, null, NOTES.E5, null, NOTES.E5, null,
    NOTES.D5, null, NOTES.D5, null, NOTES.C5, null, NOTES.B4, null,
    NOTES.A4, NOTES.C5, NOTES.E5, NOTES.A5, NOTES.Gs5, NOTES.E5, NOTES.B4, NOTES.Gs4,
    NOTES.A4, null, NOTES.A4, null, NOTES.A4, null, null, null
];

// --- LEVEL 2 TRACK: "Hungarian Dance No. 5" ---
export const BASS_PATTERN_L2: PatternArray = [
    NOTES.D2, NOTES.D3, NOTES.F2, NOTES.D3, NOTES.A2, NOTES.D3, NOTES.F2, NOTES.C3,
    NOTES.D2, NOTES.D3, NOTES.F2, NOTES.D3, NOTES.A2, NOTES.D3, NOTES.C3, NOTES.A2,
    NOTES.A2, NOTES.A3, NOTES.Cs3, NOTES.A3, NOTES.E3, NOTES.A3, NOTES.G3, NOTES.E3,
    NOTES.A2, NOTES.Cs3, NOTES.E3, NOTES.G3, NOTES.A3, NOTES.G3, NOTES.E3, NOTES.Cs3,

    NOTES.D2, NOTES.D3, NOTES.F2, NOTES.D3, NOTES.A2, NOTES.D3, NOTES.F2, NOTES.C3,
    NOTES.D2, NOTES.D3, NOTES.F2, NOTES.D3, NOTES.A2, NOTES.D3, NOTES.C3, NOTES.A2,
    NOTES.A2, NOTES.A3, NOTES.Cs3, NOTES.A3, NOTES.E3, NOTES.A3, NOTES.G3, NOTES.E3,
    NOTES.D2, NOTES.F2, NOTES.A2, NOTES.D3, NOTES.F3, NOTES.D3, NOTES.A2, NOTES.F2,

    NOTES.D2, NOTES.D3, NOTES.F2, NOTES.D3, NOTES.A2, NOTES.D3, NOTES.F2, NOTES.C3,
    NOTES.A2, NOTES.A3, NOTES.Cs3, NOTES.A3, NOTES.E3, NOTES.A3, NOTES.G3, NOTES.E3,
    NOTES.D2, NOTES.D3, NOTES.F2, NOTES.D3, NOTES.A2, NOTES.D3, NOTES.C3, NOTES.A2,
    NOTES.D2, NOTES.F2, NOTES.A2, NOTES.D3, NOTES.F3, NOTES.D3, NOTES.A2, NOTES.F2,

    NOTES.Bb2, NOTES.Bb3, NOTES.D3, NOTES.Bb3, NOTES.F3, NOTES.Bb3, NOTES.D3, NOTES.C3,
    NOTES.C2, NOTES.C3, NOTES.E3, NOTES.C3, NOTES.G3, NOTES.C3, NOTES.E3, NOTES.D3,
    NOTES.A2, NOTES.A3, NOTES.Cs3, NOTES.A3, NOTES.E3, NOTES.A3, NOTES.G3, NOTES.E3,
    NOTES.D2, NOTES.D3, NOTES.F2, NOTES.D3, NOTES.A2, NOTES.D3, NOTES.F2, NOTES.D2,

    NOTES.D2, NOTES.D2, NOTES.D2, NOTES.D2, NOTES.D2, NOTES.D2, NOTES.D2, NOTES.D2,
    NOTES.A2, NOTES.A2, NOTES.A2, NOTES.A2, NOTES.A2, NOTES.A2, NOTES.A2, NOTES.A2,
    NOTES.D2, NOTES.D2, NOTES.D2, NOTES.D2, NOTES.F2, NOTES.F2, NOTES.A2, NOTES.A2,
    NOTES.G2, NOTES.G2, NOTES.E2, NOTES.E2, NOTES.A2, NOTES.A2, NOTES.A2, NOTES.A2,

    NOTES.D2, null, NOTES.D2, null, NOTES.D2, null, NOTES.D2, null,
    NOTES.A2, null, NOTES.A2, null, NOTES.A2, null, NOTES.A2, null,
    NOTES.D2, NOTES.F2, NOTES.A2, NOTES.D3, NOTES.F3, NOTES.D3, NOTES.A2, NOTES.F2,
    NOTES.D2, null, NOTES.D2, null, NOTES.D2, null, null, null
];

export const MELODY_PATTERN_L2: PatternArray = [
    NOTES.D5, null, NOTES.F5, null, NOTES.A5, null, null, null,
    NOTES.F5, null, NOTES.D5, null, NOTES.A4, null, NOTES.F4, null,
    NOTES.E4, null, NOTES.G4, null, NOTES.Bb4, null, null, null,
    NOTES.G4, null, NOTES.E4, null, NOTES.Cs4, null, NOTES.E4, null,
    NOTES.D4, null, NOTES.F4, null, NOTES.A4, null, NOTES.D5, null,
    NOTES.F5, null, null, null, NOTES.E5, null, NOTES.D5, null,
    NOTES.Cs5, null, null, null, NOTES.E5, null, null, null,
    NOTES.D5, null, null, null, null, null, null, null,

    NOTES.D5, null, NOTES.F5, null, NOTES.A5, null, null, null,
    NOTES.F5, null, NOTES.D5, null, NOTES.A5, null, NOTES.D6, null,
    NOTES.E5, null, NOTES.G5, null, NOTES.Bb5, null, null, null,
    NOTES.G5, null, NOTES.E5, null, NOTES.Cs5, null, NOTES.E5, null,
    NOTES.D5, null, NOTES.F5, null, NOTES.A5, null, NOTES.D6, null,
    NOTES.F6, null, NOTES.E6, null, NOTES.D6, null, NOTES.Cs6, null,
    NOTES.D6, null, null, null, NOTES.A5, null, NOTES.F5, null,
    NOTES.D5, null, NOTES.A4, null, null, null, null, null,

    NOTES.D5, NOTES.F5, NOTES.A5, NOTES.D6, NOTES.Cs6, NOTES.D6, NOTES.E6, NOTES.D6,
    NOTES.Bb5, NOTES.G5, NOTES.E5, NOTES.Cs5, NOTES.D5, NOTES.E5, NOTES.F5, NOTES.G5,
    NOTES.A5, NOTES.D6, NOTES.F6, NOTES.D6, NOTES.A5, NOTES.F5, NOTES.D5, NOTES.A4,
    NOTES.G4, NOTES.Bb4, NOTES.E5, NOTES.G5, NOTES.Bb5, NOTES.A5, NOTES.G5, NOTES.E5,
    NOTES.F5, null, NOTES.D5, null, NOTES.F5, null, NOTES.A5, null,
    NOTES.G5, null, NOTES.E5, null, NOTES.Cs5, null, NOTES.A4, null,
    NOTES.D5, NOTES.E5, NOTES.F5, NOTES.G5, NOTES.A5, NOTES.Bb5, NOTES.Cs6, NOTES.D6,
    NOTES.D6, null, NOTES.D5, null, NOTES.D4, null, null, null
];

// --- LEVEL 3 TRACK: "Storm - Summer Presto" ---
export const BASS_PATTERN_L3: PatternArray = [
    NOTES.E2, NOTES.E2, NOTES.B2, NOTES.E2, NOTES.G2, NOTES.E2, NOTES.B2, NOTES.E2,
    NOTES.E2, NOTES.E2, NOTES.B2, NOTES.E2, NOTES.G2, NOTES.E2, NOTES.B2, NOTES.E2,
    NOTES.E2, NOTES.E2, NOTES.B2, NOTES.E2, NOTES.G2, NOTES.E2, NOTES.B2, NOTES.E2,
    NOTES.E2, NOTES.E2, NOTES.B2, NOTES.E2, NOTES.G2, NOTES.E2, NOTES.Fs2, NOTES.G2,

    NOTES.A2, NOTES.A2, NOTES.E3, NOTES.A2, NOTES.C3, NOTES.A2, NOTES.E3, NOTES.A2,
    NOTES.A2, NOTES.A2, NOTES.E3, NOTES.A2, NOTES.C3, NOTES.A2, NOTES.E3, NOTES.A2,
    NOTES.B2, NOTES.B2, NOTES.Fs3, NOTES.B2, NOTES.Ds3, NOTES.B2, NOTES.Fs3, NOTES.B2,
    NOTES.E2, NOTES.G2, NOTES.B2, NOTES.E3, NOTES.G3, NOTES.E3, NOTES.B2, NOTES.G2,

    NOTES.E2, NOTES.E3, NOTES.B2, NOTES.E3, NOTES.G2, NOTES.E3, NOTES.B2, NOTES.E3,
    NOTES.D2, NOTES.D3, NOTES.A2, NOTES.D3, NOTES.Fs2, NOTES.D3, NOTES.A2, NOTES.D3,
    NOTES.C2, NOTES.C3, NOTES.G2, NOTES.C3, NOTES.E2, NOTES.C3, NOTES.G2, NOTES.C3,
    NOTES.B2, NOTES.B3, NOTES.Fs3, NOTES.B3, NOTES.Ds3, NOTES.B3, NOTES.Fs3, NOTES.B2,

    NOTES.E2, NOTES.E3, NOTES.B2, NOTES.E3, NOTES.G2, NOTES.E3, NOTES.B2, NOTES.E3,
    NOTES.E2, NOTES.E3, NOTES.B2, NOTES.E3, NOTES.G2, NOTES.E3, NOTES.B2, NOTES.E3,
    NOTES.B2, NOTES.B3, NOTES.Fs3, NOTES.B3, NOTES.Ds3, NOTES.B3, NOTES.Fs3, NOTES.B2,
    NOTES.E2, NOTES.G2, NOTES.B2, NOTES.E3, NOTES.G3, NOTES.E3, NOTES.B2, NOTES.G2,

    NOTES.E2, NOTES.E2, NOTES.E2, NOTES.E2, NOTES.E2, NOTES.E2, NOTES.E2, NOTES.E2,
    NOTES.E2, NOTES.E2, NOTES.E2, NOTES.E2, NOTES.B2, NOTES.B2, NOTES.B2, NOTES.B2,
    NOTES.E2, NOTES.E2, NOTES.E2, NOTES.E2, NOTES.G2, NOTES.G2, NOTES.B2, NOTES.B2,
    NOTES.A2, NOTES.A2, NOTES.Fs2, NOTES.Fs2, NOTES.B2, NOTES.B2, NOTES.B2, NOTES.B2,

    NOTES.E2, null, NOTES.E2, null, NOTES.E2, null, NOTES.E2, null,
    NOTES.B2, null, NOTES.B2, null, NOTES.B2, null, NOTES.B2, null,
    NOTES.E2, NOTES.G2, NOTES.B2, NOTES.E3, NOTES.G3, NOTES.E3, NOTES.B2, NOTES.G2,
    NOTES.E2, null, NOTES.E2, null, NOTES.E2, null, null, null
];

export const MELODY_PATTERN_L3: PatternArray = [
    NOTES.E5, NOTES.E5, NOTES.E5, NOTES.E5, NOTES.B4, NOTES.B4, NOTES.B4, NOTES.B4,
    NOTES.G4, NOTES.G4, NOTES.E4, NOTES.E4, NOTES.B3, null, NOTES.E4, null,
    NOTES.G5, NOTES.G5, NOTES.G5, NOTES.G5, NOTES.E5, NOTES.E5, NOTES.E5, NOTES.E5,
    NOTES.B4, NOTES.B4, NOTES.G4, NOTES.G4, NOTES.E4, null, NOTES.G4, null,
    NOTES.B5, NOTES.G5, NOTES.E5, NOTES.B4, NOTES.G5, NOTES.E5, NOTES.B4, NOTES.G4,
    NOTES.E5, NOTES.B4, NOTES.G4, NOTES.E4, NOTES.Fs4, NOTES.G4, NOTES.A4, NOTES.B4,
    NOTES.C5, NOTES.B4, NOTES.A4, NOTES.G4, NOTES.Fs4, NOTES.E4, NOTES.Ds4, NOTES.Fs4,
    NOTES.E4, null, NOTES.E5, null, NOTES.E4, null, null, null,

    NOTES.E5, NOTES.B5, NOTES.G5, NOTES.B5, NOTES.E5, NOTES.B5, NOTES.G5, NOTES.B5,
    NOTES.E5, NOTES.B5, NOTES.G5, NOTES.B5, NOTES.E5, NOTES.B5, NOTES.G5, NOTES.B5,
    NOTES.D5, NOTES.B5, NOTES.Fs5, NOTES.B5, NOTES.D5, NOTES.B5, NOTES.Fs5, NOTES.B5,
    NOTES.D5, NOTES.B5, NOTES.Fs5, NOTES.B5, NOTES.D5, NOTES.B5, NOTES.Fs5, NOTES.B5,
    NOTES.C5, NOTES.A5, NOTES.E5, NOTES.A5, NOTES.C5, NOTES.A5, NOTES.E5, NOTES.A5,
    NOTES.B4, NOTES.G5, NOTES.E5, NOTES.G5, NOTES.A4, NOTES.Fs5, NOTES.Ds5, NOTES.Fs5,
    NOTES.E5, NOTES.B4, NOTES.G4, NOTES.B4, NOTES.E5, NOTES.B4, NOTES.G4, NOTES.B4,
    NOTES.E5, null, NOTES.B4, null, NOTES.E5, null, null, null,

    NOTES.E6, NOTES.Ds6, NOTES.E6, NOTES.B5, NOTES.G5, NOTES.E5, NOTES.Ds5, NOTES.E5,
    NOTES.B4, NOTES.G4, NOTES.Fs4, NOTES.G4, NOTES.E4, NOTES.Ds4, NOTES.E4, NOTES.Fs4,
    NOTES.G4, NOTES.Gs4, NOTES.A4, NOTES.As4, NOTES.B4, NOTES.C5, NOTES.Cs5, NOTES.D5,
    NOTES.Ds5, NOTES.E5, NOTES.Fs5, NOTES.G5, NOTES.A5, NOTES.B5, NOTES.C6, NOTES.Ds6,
    NOTES.E6, null, NOTES.E6, null, NOTES.B5, null, NOTES.B5, null,
    NOTES.G5, null, NOTES.G5, null, NOTES.E5, null, NOTES.E5, null,
    NOTES.E5, NOTES.G5, NOTES.B5, NOTES.E6, NOTES.B5, NOTES.G5, NOTES.E5, NOTES.B4,
    NOTES.E5, null, NOTES.E5, null, NOTES.E5, null, null, null
];

// --- LEVEL 4 TRACK: "Maple Leaf Rag" ---
export const BASS_PATTERN_L4: PatternArray = [
    NOTES.C2, null, NOTES.C2, null, NOTES.G2, null, NOTES.G2, null,
    NOTES.C2, null, NOTES.C2, null, NOTES.G2, null, NOTES.G2, null,
    NOTES.G2, null, NOTES.G2, null, NOTES.D2, null, NOTES.D2, null,
    NOTES.C2, null, NOTES.C2, null, NOTES.G2, null, NOTES.G2, null,

    NOTES.C2, null, NOTES.C2, null, NOTES.G2, null, NOTES.G2, null,
    NOTES.C2, null, NOTES.C2, null, NOTES.G2, null, NOTES.G2, null,
    NOTES.F2, null, NOTES.F2, null, NOTES.G2, null, NOTES.G2, null,
    NOTES.C2, null, NOTES.E2, null, NOTES.G2, null, NOTES.C2, null,

    NOTES.C2, null, NOTES.C2, null, NOTES.G2, null, NOTES.G2, null,
    NOTES.C2, null, NOTES.C2, null, NOTES.G2, null, NOTES.G2, null,
    NOTES.G2, null, NOTES.G2, null, NOTES.D2, null, NOTES.D2, null,
    NOTES.C2, null, NOTES.C2, null, NOTES.G2, null, NOTES.G2, null,

    NOTES.C2, null, NOTES.C2, null, NOTES.G2, null, NOTES.G2, null,
    NOTES.C2, null, NOTES.C2, null, NOTES.G2, null, NOTES.G2, null,
    NOTES.F2, null, NOTES.F2, null, NOTES.G2, null, NOTES.G2, null,
    NOTES.C2, null, NOTES.E2, null, NOTES.G2, null, NOTES.C2, null,

    NOTES.C2, null, NOTES.C2, null, NOTES.G2, null, NOTES.G2, null,
    NOTES.F2, null, NOTES.F2, null, NOTES.F2, null, NOTES.F2, null,
    NOTES.G2, null, NOTES.G2, null, NOTES.G2, null, NOTES.G2, null,
    NOTES.C2, null, NOTES.E2, null, NOTES.G2, null, NOTES.C2, null,

    NOTES.C2, null, NOTES.C2, null, NOTES.G2, null, NOTES.G2, null,
    NOTES.G2, null, NOTES.G2, null, NOTES.G2, null, NOTES.G2, null,
    NOTES.C2, null, NOTES.E2, null, NOTES.G2, null, NOTES.E2, null,
    NOTES.C2, null, NOTES.C2, null, NOTES.C2, null, null, null
];

export const MELODY_PATTERN_L4: PatternArray = [
    NOTES.C5, null, NOTES.E5, null, NOTES.G5, null, NOTES.C6, null,
    NOTES.E6, null, null, NOTES.C6, null, NOTES.E6, null, null,
    NOTES.G5, null, NOTES.C6, null, NOTES.E6, null, NOTES.G6, null,
    NOTES.E6, null, null, NOTES.C6, null, NOTES.G5, null, null,
    NOTES.A5, null, NOTES.C6, null, NOTES.E6, null, NOTES.G5, null,
    NOTES.A5, null, NOTES.C6, null, NOTES.E6, null, NOTES.D6, null,
    NOTES.C6, null, null, null, NOTES.G5, null, null, null,
    NOTES.C5, null, null, null, null, null, null, null,

    NOTES.G5, NOTES.A5, NOTES.Bb5, NOTES.B5, NOTES.C6, NOTES.E6, NOTES.G6, NOTES.E6,
    NOTES.C6, NOTES.A5, NOTES.F5, NOTES.D5, NOTES.C5, NOTES.E5, NOTES.G5, null,
    NOTES.G5, NOTES.A5, NOTES.Bb5, NOTES.B5, NOTES.C6, NOTES.E6, NOTES.G6, NOTES.E6,
    NOTES.D6, NOTES.C6, NOTES.B5, NOTES.A5, NOTES.G5, null, NOTES.B5, null,
    NOTES.E6, NOTES.D6, NOTES.C6, NOTES.A5, NOTES.G5, NOTES.E5, NOTES.C5, NOTES.G4,
    NOTES.A4, NOTES.C5, NOTES.E5, NOTES.G5, NOTES.C6, NOTES.D6, NOTES.E6, NOTES.F6,
    NOTES.G6, null, NOTES.E6, null, NOTES.C6, null, NOTES.G5, null,
    NOTES.C6, null, null, null, null, null, null, null,

    NOTES.C5, NOTES.Ds5, NOTES.E5, NOTES.G5, NOTES.C6, NOTES.Ds6, NOTES.E6, NOTES.G6,
    NOTES.A6, NOTES.G6, NOTES.E6, NOTES.C6, NOTES.A5, NOTES.G5, NOTES.E5, NOTES.C5,
    NOTES.D5, NOTES.F5, NOTES.A5, NOTES.C6, NOTES.D6, NOTES.F6, NOTES.A6, NOTES.F6,
    NOTES.D6, NOTES.C6, NOTES.B5, NOTES.A5, NOTES.G5, NOTES.F5, NOTES.E5, NOTES.D5,
    NOTES.C6, null, NOTES.E6, null, NOTES.G6, null, NOTES.C6, null,
    NOTES.B5, null, NOTES.D6, null, NOTES.G6, null, NOTES.B5, null,
    NOTES.C5, NOTES.E5, NOTES.G5, NOTES.C6, NOTES.E6, NOTES.G6, NOTES.C6, NOTES.E6,
    NOTES.C6, null, NOTES.C6, null, NOTES.C6, null, null, null
];

// --- LEVEL 5 TRACK: Mozart Sonata K.310 ---
export const BASS_PATTERN_L5: PatternArray = [
    NOTES.A2, NOTES.E3, NOTES.A3, NOTES.E3, NOTES.C3, NOTES.E3, NOTES.A3, NOTES.E3,
    NOTES.A2, NOTES.E3, NOTES.A3, NOTES.E3, NOTES.C3, NOTES.E3, NOTES.B2, NOTES.Gs2,
    NOTES.E2, NOTES.B2, NOTES.E3, NOTES.Gs3, NOTES.B3, NOTES.Gs3, NOTES.E3, NOTES.B2,
    NOTES.E2, NOTES.B2, NOTES.E3, NOTES.Gs3, NOTES.B3, NOTES.Gs3, NOTES.E3, NOTES.B2,
    NOTES.F2, NOTES.C3, NOTES.F3, NOTES.A3, NOTES.C3, NOTES.A3, NOTES.F3, NOTES.C3,
    NOTES.D2, NOTES.A2, NOTES.D3, NOTES.F3, NOTES.A3, NOTES.F3, NOTES.D3, NOTES.A2,
    NOTES.E2, NOTES.B2, NOTES.E3, NOTES.Gs3, NOTES.B3, NOTES.Gs3, NOTES.E3, NOTES.B2,
    NOTES.A2, NOTES.E3, NOTES.A3, NOTES.C3, NOTES.E3, NOTES.C3, NOTES.B2, NOTES.Gs2,

    NOTES.A2, NOTES.E3, NOTES.C3, NOTES.E3, NOTES.A3, NOTES.E3, NOTES.C3, NOTES.E3,
    NOTES.A2, NOTES.E3, NOTES.C3, NOTES.E3, NOTES.B2, NOTES.E3, NOTES.Gs3, NOTES.E3,
    NOTES.C2, NOTES.G2, NOTES.E3, NOTES.G3, NOTES.C3, NOTES.G3, NOTES.E3, NOTES.G3,
    NOTES.G2, NOTES.D3, NOTES.B2, NOTES.D3, NOTES.G3, NOTES.D3, NOTES.B2, NOTES.D3,
    NOTES.D2, NOTES.A2, NOTES.F3, NOTES.A3, NOTES.D3, NOTES.A3, NOTES.F3, NOTES.A3,
    NOTES.F2, NOTES.C3, NOTES.A3, NOTES.C3, NOTES.F3, NOTES.C3, NOTES.A2, NOTES.C3,
    NOTES.E2, NOTES.B2, NOTES.Gs3, NOTES.B3, NOTES.E3, NOTES.B3, NOTES.Gs3, NOTES.B3,
    NOTES.E2, NOTES.B2, NOTES.E3, NOTES.Gs3, NOTES.B3, NOTES.Gs3, NOTES.E3, NOTES.B2,

    NOTES.A2, NOTES.A2, NOTES.E3, NOTES.E3, NOTES.A3, NOTES.A3, NOTES.E3, NOTES.E3,
    NOTES.C3, NOTES.C3, NOTES.E3, NOTES.E3, NOTES.B2, NOTES.B2, NOTES.Gs2, NOTES.Gs2,
    NOTES.F2, NOTES.F2, NOTES.C3, NOTES.C3, NOTES.D2, NOTES.D2, NOTES.A2, NOTES.A2,
    NOTES.E2, NOTES.E2, NOTES.B2, NOTES.B2, NOTES.E3, NOTES.E3, NOTES.Gs2, NOTES.Gs2,
    NOTES.E2, NOTES.B2, NOTES.E3, NOTES.B2, NOTES.E2, NOTES.B2, NOTES.E3, NOTES.B2,
    NOTES.E2, NOTES.B2, NOTES.E3, NOTES.Gs3, NOTES.B3, NOTES.Gs3, NOTES.E3, NOTES.B2,
    NOTES.A2, NOTES.C3, NOTES.E3, NOTES.A3, NOTES.E3, NOTES.C3, NOTES.B2, NOTES.Gs2,
    NOTES.A2, null, NOTES.E2, null, NOTES.A2, null, NOTES.A2, null
];

export const MELODY_PATTERN_L5: PatternArray = [
    NOTES.A5, null, NOTES.A5, null, NOTES.E6, null, NOTES.E6, null,
    NOTES.C6, null, NOTES.A5, null, NOTES.Gs5, null, NOTES.E5, null,
    NOTES.A5, null, NOTES.C6, null, NOTES.B5, null, NOTES.A5, null,
    NOTES.Gs5, null, NOTES.B5, null, NOTES.E6, null, null, null,
    NOTES.F5, null, NOTES.A5, null, NOTES.C6, null, NOTES.A5, null,
    NOTES.D6, null, NOTES.C6, null, NOTES.B5, null, NOTES.A5, null,
    NOTES.E6, null, NOTES.D6, null, NOTES.C6, null, NOTES.B5, null,
    NOTES.A5, null, NOTES.Gs5, null, NOTES.A5, null, null, null,

    NOTES.A4, NOTES.B4, NOTES.C5, NOTES.D5, NOTES.E5, NOTES.F5, NOTES.Gs5, NOTES.A5,
    NOTES.Gs5, NOTES.F5, NOTES.E5, NOTES.D5, NOTES.C5, NOTES.B4, NOTES.A4, NOTES.E5,
    NOTES.C5, NOTES.E5, NOTES.G5, NOTES.C6, NOTES.B5, NOTES.G5, NOTES.E5, NOTES.C5,
    NOTES.D5, NOTES.F5, NOTES.G5, NOTES.B5, NOTES.A5, NOTES.F5, NOTES.D5, NOTES.B4,
    NOTES.D5, NOTES.F5, NOTES.A5, NOTES.D6, NOTES.C6, NOTES.A5, NOTES.F5, NOTES.D5,
    NOTES.F5, NOTES.A5, NOTES.C6, NOTES.F6, NOTES.E6, NOTES.C6, NOTES.A5, NOTES.F5,
    NOTES.E5, NOTES.F5, NOTES.E5, NOTES.Ds5, NOTES.E5, NOTES.F5, NOTES.E5, NOTES.Ds5,
    NOTES.E5, NOTES.Gs5, NOTES.B5, NOTES.E6, NOTES.D6, NOTES.B5, NOTES.Gs5, NOTES.E5,

    NOTES.A5, NOTES.A5, NOTES.C6, NOTES.C6, NOTES.E6, NOTES.E6, NOTES.A6, NOTES.A6,
    NOTES.Gs6, NOTES.F6, NOTES.E6, NOTES.D6, NOTES.C6, NOTES.B5, NOTES.A5, NOTES.Gs5,
    NOTES.F6, NOTES.E6, NOTES.D6, NOTES.C6, NOTES.B5, NOTES.A5, NOTES.Gs5, NOTES.F5,
    NOTES.E5, NOTES.D5, NOTES.C5, NOTES.B4, NOTES.A4, NOTES.B4, NOTES.C5, NOTES.D5,
    NOTES.E5, null, NOTES.E5, null, NOTES.Gs5, null, NOTES.Gs5, null,
    NOTES.B5, NOTES.C6, NOTES.D6, NOTES.E6, NOTES.F6, NOTES.E6, NOTES.D6, NOTES.B5,
    NOTES.A5, NOTES.C6, NOTES.E6, NOTES.A6, NOTES.Gs6, NOTES.E6, NOTES.B5, NOTES.Gs5,
    NOTES.A5, null, NOTES.E5, null, NOTES.A5, null, null, null
];

// --- MENU TRACK: "Cosmic Legato - Ambient Space Horizon" ---
export const MENU_BASS_PATTERN: PatternArray = [
    NOTES.C2, NOTES.C2, NOTES.C3, NOTES.C3, NOTES.G2, NOTES.G2, NOTES.C3, NOTES.C3,
    NOTES.C2, NOTES.C2, NOTES.G2, NOTES.G2, NOTES.C3, NOTES.C3, NOTES.G2, NOTES.G2,
    NOTES.C2, NOTES.C2, NOTES.Eb2, NOTES.Eb2, NOTES.G2, NOTES.G2, NOTES.C3, NOTES.C3,
    NOTES.G2, NOTES.G2, NOTES.Eb2, NOTES.Eb2, NOTES.C2, NOTES.C2, NOTES.G2, NOTES.G2,
    NOTES.Ab2, NOTES.Ab2, NOTES.C3, NOTES.C3, NOTES.Eb3, NOTES.Eb3, NOTES.Ab2, NOTES.Ab2,
    NOTES.C3, NOTES.C3, NOTES.Eb3, NOTES.Eb3, NOTES.Ab2, NOTES.Ab2, NOTES.C3, NOTES.C3,
    NOTES.F2, NOTES.F2, NOTES.C3, NOTES.C3, NOTES.F2, NOTES.F2, NOTES.Ab2, NOTES.Ab2,
    NOTES.C3, NOTES.C3, NOTES.F2, NOTES.F2, NOTES.Ab2, NOTES.Ab2, NOTES.C3, NOTES.C3,

    NOTES.Bb2, NOTES.Bb2, NOTES.D3, NOTES.D3, NOTES.F3, NOTES.F3, NOTES.Bb2, NOTES.Bb2,
    NOTES.D3, NOTES.D3, NOTES.F3, NOTES.F3, NOTES.Bb2, NOTES.Bb2, NOTES.D3, NOTES.D3,
    NOTES.G2, NOTES.G2, NOTES.D3, NOTES.D3, NOTES.G2, NOTES.G2, NOTES.Bb2, NOTES.Bb2,
    NOTES.D3, NOTES.D3, NOTES.G2, NOTES.G2, NOTES.Bb2, NOTES.Bb2, NOTES.D3, NOTES.D3,
    NOTES.Eb2, NOTES.Eb2, NOTES.G2, NOTES.G2, NOTES.Bb2, NOTES.Bb2, NOTES.Eb3, NOTES.Eb3,
    NOTES.Bb2, NOTES.Bb2, NOTES.G2, NOTES.G2, NOTES.Eb2, NOTES.Eb2, NOTES.G2, NOTES.G2,
    NOTES.C2, NOTES.C2, NOTES.G2, NOTES.G2, NOTES.C3, NOTES.C3, NOTES.Eb3, NOTES.Eb3,
    NOTES.C3, NOTES.C3, NOTES.G2, NOTES.G2, NOTES.C2, NOTES.C2, NOTES.G2, NOTES.G2,

    NOTES.Ab2, NOTES.Ab2, NOTES.C3, NOTES.C3, NOTES.Eb3, NOTES.Eb3, NOTES.Ab3, NOTES.Ab3,
    NOTES.Eb3, NOTES.Eb3, NOTES.C3, NOTES.C3, NOTES.Ab2, NOTES.Ab2, NOTES.C3, NOTES.C3,
    NOTES.Bb2, NOTES.Bb2, NOTES.D3, NOTES.D3, NOTES.F3, NOTES.F3, NOTES.Bb3, NOTES.Bb3,
    NOTES.F3, NOTES.F3, NOTES.D3, NOTES.D3, NOTES.Bb2, NOTES.Bb2, NOTES.D3, NOTES.D3,
    NOTES.G2, NOTES.G2, NOTES.D3, NOTES.D3, NOTES.F3, NOTES.F3, NOTES.G3, NOTES.G3,
    NOTES.F3, NOTES.F3, NOTES.D3, NOTES.D3, NOTES.G2, NOTES.G2, NOTES.D3, NOTES.D3,
    NOTES.C2, NOTES.C2, NOTES.G2, NOTES.G2, NOTES.C3, NOTES.C3, NOTES.Eb3, NOTES.Eb3,
    NOTES.C3, NOTES.C3, NOTES.G2, NOTES.G2, NOTES.C2, null,     NOTES.C2, null
];

export const MENU_CHIME_PATTERN: PatternArray = [
    NOTES.C5, NOTES.Eb5, NOTES.G5, NOTES.Bb5, NOTES.C6, NOTES.Eb6, NOTES.D6, NOTES.Bb5,
    NOTES.G5, NOTES.Eb5, NOTES.C5, NOTES.G4, NOTES.C5, NOTES.Eb5, NOTES.G5, NOTES.Bb5,
    NOTES.C6, NOTES.Eb6, NOTES.F6, NOTES.G6, NOTES.Eb6, NOTES.D6, NOTES.C6, NOTES.Bb5,
    NOTES.G5, NOTES.Bb5, NOTES.C6, NOTES.D6, NOTES.C6, NOTES.G5, NOTES.Eb5, NOTES.G5,
    NOTES.Ab5, NOTES.C6, NOTES.Eb6, NOTES.G6, NOTES.F6, NOTES.Eb6, NOTES.C6, NOTES.Ab5,
    NOTES.Eb5, NOTES.Ab5, NOTES.C6, NOTES.Eb6, NOTES.C6, NOTES.Ab5, NOTES.Eb5, NOTES.C5,
    NOTES.F5, NOTES.Ab5, NOTES.C6, NOTES.Eb6, NOTES.D6, NOTES.C6, NOTES.Bb5, NOTES.G5,
    NOTES.Eb5, NOTES.G5, NOTES.Bb5, NOTES.C6, NOTES.Bb5, NOTES.G5, NOTES.Eb5, NOTES.C5,

    NOTES.Bb5, NOTES.D6, NOTES.F6, NOTES.G6, NOTES.F6, NOTES.D6, NOTES.Bb5, NOTES.G5,
    NOTES.D5, NOTES.G5, NOTES.Bb5, NOTES.D6, NOTES.Bb5, NOTES.G5, NOTES.D5, NOTES.Bb4,
    NOTES.G6, NOTES.F6, NOTES.Eb6, NOTES.D6, NOTES.C6, NOTES.Bb5, NOTES.Ab5, NOTES.G5,
    NOTES.Eb5, NOTES.G5, NOTES.Bb5, NOTES.C6, NOTES.D6, NOTES.Eb6, NOTES.F6, NOTES.G6,
    NOTES.Eb5, NOTES.G5, NOTES.Bb5, NOTES.C6, NOTES.D6, NOTES.Eb6, NOTES.G6, NOTES.Eb6,
    NOTES.C6, NOTES.Bb5, NOTES.G5, NOTES.Eb5, NOTES.Bb4, NOTES.Eb5, NOTES.G5, NOTES.Bb5,
    NOTES.C6, NOTES.D6, NOTES.Eb6, NOTES.F6, NOTES.G6, NOTES.Eb6, NOTES.D6, NOTES.C6,
    NOTES.Bb5, NOTES.G5, NOTES.Eb5, NOTES.C5, NOTES.G4, NOTES.C5, NOTES.Eb5, NOTES.G5,

    NOTES.Ab5, NOTES.C6, NOTES.Eb6, NOTES.G6, NOTES.Ab6, NOTES.G6, NOTES.Eb6, NOTES.C6,
    NOTES.Ab5, NOTES.Eb5, NOTES.Ab5, NOTES.C6, NOTES.Eb6, NOTES.G6, NOTES.Eb6, NOTES.C6,
    NOTES.F6, NOTES.Eb6, NOTES.D6, NOTES.C6, NOTES.Bb5, NOTES.G5, NOTES.Eb5, NOTES.D5,
    NOTES.Bb4, NOTES.D5, NOTES.F5, NOTES.Bb5, NOTES.D6, NOTES.F6, NOTES.D6, NOTES.Bb5,
    NOTES.G5, NOTES.B5, NOTES.D6, NOTES.F6, NOTES.G6, NOTES.F6, NOTES.D6, NOTES.B5,
    NOTES.G5, NOTES.D5, NOTES.G5, NOTES.B5, NOTES.D6, NOTES.F6, NOTES.D6, NOTES.B5,
    NOTES.C6, NOTES.G5, NOTES.Eb5, NOTES.C5, NOTES.G4, NOTES.C5, NOTES.Eb5, NOTES.G5,
    NOTES.C6, null,     NOTES.G5, null,     NOTES.C5, null,     null,     null
];

// --- LEVEL 7 (BOSS LEVEL) TRACK: "Toccata and Fugue in D minor, BWV 565" (J. S. Bach) ---
export const BASS_PATTERN_L7: PatternArray = [
    // --- Section 1: Opening Toccata Pedal Stabs (Steps 0 - 47) ---
    NOTES.D2, null, NOTES.D2, null, NOTES.D2, null, NOTES.D3, null,
    NOTES.D2, null, null, null, NOTES.D2, null, null, null,

    NOTES.D2, null, NOTES.D2, null, NOTES.D2, null, NOTES.D3, null,
    NOTES.D2, null, null, null, NOTES.D2, null, null, null,

    NOTES.Cs2, NOTES.Cs2, NOTES.E2, NOTES.E2, NOTES.G2, NOTES.G2, NOTES.Bb2, NOTES.Bb2,
    NOTES.A2, NOTES.A2, NOTES.G2, NOTES.F2, NOTES.E2, NOTES.E2, NOTES.A2, NOTES.A2,

    NOTES.D2, null, NOTES.D2, null, NOTES.D2, null, NOTES.D3, null,
    NOTES.D2, null, null, null, NOTES.D2, null, null, null,

    NOTES.Cs2, NOTES.Cs2, NOTES.E2, NOTES.E2, NOTES.G2, NOTES.G2, NOTES.Bb2, NOTES.Bb2,
    NOTES.A2, NOTES.A2, NOTES.G2, NOTES.F2, NOTES.E2, NOTES.E2, NOTES.A2, NOTES.A2,

    // --- Section 2: Driving Fugue Bass Motor (Steps 48 - 111) ---
    NOTES.D2, NOTES.D3, NOTES.D2, NOTES.D3, NOTES.F2, NOTES.D3, NOTES.A2, NOTES.D3,
    NOTES.D2, NOTES.D3, NOTES.F2, NOTES.D3, NOTES.A2, NOTES.D3, NOTES.F2, NOTES.D3,

    NOTES.Bb2, NOTES.Bb3, NOTES.F2, NOTES.Bb3, NOTES.G2, NOTES.Bb3, NOTES.F2, NOTES.Bb3,
    NOTES.A2, NOTES.A3, NOTES.E2, NOTES.A3, NOTES.F2, NOTES.A3, NOTES.E2, NOTES.A3,

    NOTES.D2, NOTES.D3, NOTES.F2, NOTES.D3, NOTES.A2, NOTES.D3, NOTES.F2, NOTES.D3,
    NOTES.D2, NOTES.F2, NOTES.A2, NOTES.D3, NOTES.F3, NOTES.D3, NOTES.A2, NOTES.F2,

    NOTES.G2, NOTES.G3, NOTES.D3, NOTES.G3, NOTES.E2, NOTES.E3, NOTES.Bb2, NOTES.E3,
    NOTES.A2, NOTES.A3, NOTES.E3, NOTES.A3, NOTES.A2, NOTES.A2, NOTES.A2, NOTES.A2,

    // --- Section 3: Dominant Pedal & Diminished Stabs (Steps 112 - 159) ---
    NOTES.A2, NOTES.A3, NOTES.E3, NOTES.A3, NOTES.Cs3, NOTES.A3, NOTES.E3, NOTES.A3,
    NOTES.A2, NOTES.A3, NOTES.E3, NOTES.A3, NOTES.G2, NOTES.A3, NOTES.F2, NOTES.E2,

    NOTES.Cs2, NOTES.Cs3, NOTES.E3, NOTES.Cs3, NOTES.G2, NOTES.Cs3, NOTES.E3, NOTES.Cs3,
    NOTES.A2, NOTES.A3, NOTES.G2, NOTES.F2, NOTES.E2, NOTES.E2, NOTES.E2, NOTES.E2,

    NOTES.Bb2, NOTES.Bb2, NOTES.G2, NOTES.G2, NOTES.Cs2, NOTES.Cs2, NOTES.E2, NOTES.E2,
    NOTES.D2, NOTES.D2, NOTES.F2, NOTES.F2, NOTES.A2, NOTES.A2, NOTES.D3, NOTES.D3,

    // --- Section 4: Thunderous Climax & Grand Cadence (Steps 160 - 191) ---
    NOTES.D2, NOTES.D2, NOTES.D3, NOTES.D3, NOTES.F2, NOTES.F2, NOTES.A2, NOTES.A2,
    NOTES.G2, NOTES.G2, NOTES.E2, NOTES.E2, NOTES.A2, NOTES.A2, NOTES.A2, NOTES.A2,

    NOTES.Bb2, NOTES.Bb2, NOTES.A2, NOTES.A2, NOTES.G2, NOTES.G2, NOTES.F2, NOTES.F2,
    NOTES.E2, NOTES.E2, NOTES.A2, NOTES.A2, NOTES.D2, null, NOTES.D2, null
];

export const MELODY_PATTERN_L7: PatternArray = [
    // --- Section 1: Iconic Opening Toccata Fanfare (Steps 0 - 47) ---
    NOTES.A5, NOTES.G5, NOTES.A5, null, NOTES.G5, NOTES.F5, NOTES.E5, NOTES.D5,
    NOTES.Cs5, NOTES.D5, null, null, NOTES.D5, null, null, null,

    NOTES.A4, NOTES.G4, NOTES.A4, null, NOTES.G4, NOTES.F4, NOTES.E4, NOTES.D4,
    NOTES.Cs4, NOTES.D4, null, null, NOTES.D4, null, null, null,

    NOTES.Cs4, NOTES.E4, NOTES.G4, NOTES.Bb4, NOTES.Cs5, NOTES.E5, NOTES.G5, NOTES.Bb5,
    NOTES.A5, null, NOTES.G5, NOTES.F5, NOTES.E5, NOTES.D5, NOTES.Cs5, NOTES.D5,

    NOTES.A5, NOTES.G5, NOTES.A5, null, NOTES.G5, NOTES.F5, NOTES.E5, NOTES.D5,
    NOTES.Cs5, NOTES.D5, null, null, NOTES.D5, null, null, null,

    NOTES.Cs4, NOTES.E4, NOTES.G4, NOTES.Bb4, NOTES.Cs5, NOTES.E5, NOTES.G5, NOTES.Bb5,
    NOTES.A5, null, NOTES.G5, NOTES.F5, NOTES.E5, NOTES.D5, NOTES.Cs5, NOTES.D5,

    // --- Section 2: Famous Fugue Motor Subject (Steps 48 - 111) ---
    NOTES.A5, NOTES.G5, NOTES.F5, NOTES.E5, NOTES.F5, NOTES.D5, NOTES.Cs5, NOTES.D5,
    NOTES.A4, NOTES.G4, NOTES.F4, NOTES.E4, NOTES.F4, NOTES.D4, NOTES.Cs4, NOTES.D4,

    NOTES.D5, NOTES.E5, NOTES.F5, NOTES.G5, NOTES.A5, NOTES.Bb5, NOTES.A5, NOTES.G5,
    NOTES.F5, NOTES.E5, NOTES.D5, NOTES.Cs5, NOTES.D5, NOTES.E5, NOTES.F5, NOTES.G5,

    NOTES.A5, NOTES.G5, NOTES.F5, NOTES.E5, NOTES.F5, NOTES.D5, NOTES.Cs5, NOTES.D5,
    NOTES.D6, NOTES.Cs6, NOTES.D6, NOTES.A5, NOTES.F5, NOTES.D5, NOTES.F5, NOTES.A5,

    NOTES.D6, NOTES.C6, NOTES.Bb5, NOTES.A5, NOTES.Bb5, NOTES.A5, NOTES.G5, NOTES.F5,
    NOTES.G5, NOTES.F5, NOTES.E5, NOTES.D5, NOTES.Cs5, NOTES.D5, NOTES.E5, NOTES.Cs5,

    // --- Section 3: Dominant Modulation & Arpeggiated Organ Waves (Steps 112 - 159) ---
    NOTES.E5, NOTES.F5, NOTES.E5, NOTES.D5, NOTES.Cs5, NOTES.B4, NOTES.Cs5, NOTES.A4,
    NOTES.E5, NOTES.G5, NOTES.F5, NOTES.E5, NOTES.D5, NOTES.F5, NOTES.E5, NOTES.D5,

    NOTES.Cs5, NOTES.E5, NOTES.A5, NOTES.Cs6, NOTES.E6, NOTES.D6, NOTES.Cs6, NOTES.B5,
    NOTES.A5, NOTES.G5, NOTES.F5, NOTES.E5, NOTES.D5, NOTES.Cs5, NOTES.B4, NOTES.A4,

    NOTES.Bb5, NOTES.G5, NOTES.E5, NOTES.Cs5, NOTES.Bb4, NOTES.Cs5, NOTES.E5, NOTES.G5,
    NOTES.A5, NOTES.F5, NOTES.D5, NOTES.A4, NOTES.F4, NOTES.A4, NOTES.D5, NOTES.F5,

    // --- Section 4: Presto Virtuoso Finale & Grand Cadence (Steps 160 - 191) ---
    NOTES.D6, NOTES.Cs6, NOTES.D6, NOTES.A5, NOTES.F5, NOTES.D5, NOTES.F5, NOTES.A5,
    NOTES.D6, NOTES.F6, NOTES.E6, NOTES.D6, NOTES.Cs6, NOTES.B5, NOTES.A5, NOTES.G5,

    NOTES.F5, NOTES.E5, NOTES.D5, NOTES.Cs5, NOTES.D5, NOTES.F5, NOTES.A5, NOTES.D6,
    NOTES.Cs6, NOTES.D6, NOTES.E6, NOTES.F6, NOTES.D6, null, NOTES.D6, null
];
